#spring:
#  r2dbc:
#    url: r2dbc:h2:mem:///test
#    username: sa
#    password:

webclient:
  h2-console-port: 8081

server:
  port: 15500

#spring:
#  datasource:
#    hikari:
#      data-source-class-name: oracle
#  r2dbc:
#    url: r2dbc:oracle://localhost:1521/xe
#    username: system
#    password: oracle

